/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sprd_freetype_FreeTypeJni */

#ifndef _Included_com_sprd_freetype_FreeTypeJni
#define _Included_com_sprd_freetype_FreeTypeJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sprd_freetype_FreeTypeJni
 * Method:    setFont
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sprd_freetype_FreeTypeJni_setFont
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_sprd_freetype_FreeTypeJni
 * Method:    getTextSize
 * Signature: (Ljava/lang/String;IDI[I[D)V
 */
JNIEXPORT void JNICALL Java_com_sprd_freetype_FreeTypeJni_getTextSize
  (JNIEnv *, jclass, jstring, jint, jdouble, jint, jintArray, jdoubleArray);

/*
 * Class:     com_sprd_freetype_FreeTypeJni
 * Method:    putText
 * Signature: (JLjava/lang/String;DDIDDDDDI)V
 */
JNIEXPORT void JNICALL Java_com_sprd_freetype_FreeTypeJni_putText
  (JNIEnv *, jclass, jlong, jstring, jdouble, jdouble, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jint);

/*
 * Class:     com_sprd_freetype_FreeTypeJni
 * Method:    putWText
 * Signature: (JLjava/lang/String;DDIDDDDDI)V
 */
JNIEXPORT void JNICALL Java_com_sprd_freetype_FreeTypeJni_putWText
  (JNIEnv *, jclass, jlong, jstring, jdouble, jdouble, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
