/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_watermark_WaterMarkJni */

#ifndef _Included_com_android_watermark_WaterMarkJni
#define _Included_com_android_watermark_WaterMarkJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_watermark_WaterMarkJni
 * Method:    startWaterMarkEngine
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_android_watermark_WaterMarkJni_startWaterMarkEngine
  (JNIEnv *, jclass);

/*
 * Class:     com_android_watermark_WaterMarkJni
 * Method:    Yv12ToI420
 * Signature: (J[B[BII)V
 */
JNIEXPORT void JNICALL Java_com_android_watermark_WaterMarkJni_Yv12ToI420
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_android_watermark_WaterMarkJni
 * Method:    I420ToYv12
 * Signature: (J[B[BII)V
 */
JNIEXPORT void JNICALL Java_com_android_watermark_WaterMarkJni_I420ToYv12
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_android_watermark_WaterMarkJni
 * Method:    Nv21ToI420
 * Signature: (J[B[BII)V
 */
JNIEXPORT void JNICALL Java_com_android_watermark_WaterMarkJni_Nv21ToI420
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_android_watermark_WaterMarkJni
 * Method:    I420ToNv21
 * Signature: (J[B[BII)V
 */
JNIEXPORT void JNICALL Java_com_android_watermark_WaterMarkJni_I420ToNv21
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_android_watermark_WaterMarkJni
 * Method:    Nv21ToYV12
 * Signature: (J[B[BII)V
 */
JNIEXPORT void JNICALL Java_com_android_watermark_WaterMarkJni_Nv21ToYV12
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_android_watermark_WaterMarkJni
 * Method:    YV12ToNv21
 * Signature: (J[B[BII)V
 */
JNIEXPORT void JNICALL Java_com_android_watermark_WaterMarkJni_YV12ToNv21
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_android_watermark_WaterMarkJni
 * Method:    Nv21ToNv12
 * Signature: (J[B[BII)V
 */
JNIEXPORT void JNICALL Java_com_android_watermark_WaterMarkJni_Nv21ToNv12
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_android_watermark_WaterMarkJni
 * Method:    Nv12ToNv21
 * Signature: (J[B[BII)V
 */
JNIEXPORT void JNICALL Java_com_android_watermark_WaterMarkJni_Nv12ToNv21
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_android_watermark_WaterMarkJni
 * Method:    cutCommonYuv
 * Signature: (JIII[BII[BII)V
 */
JNIEXPORT void JNICALL Java_com_android_watermark_WaterMarkJni_cutCommonYuv
  (JNIEnv *, jclass, jlong, jint, jint, jint, jbyteArray, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     com_android_watermark_WaterMarkJni
 * Method:    getSpecYuvBuffer
 * Signature: (JI[B[BIIII)V
 */
JNIEXPORT void JNICALL Java_com_android_watermark_WaterMarkJni_getSpecYuvBuffer
  (JNIEnv *, jclass, jlong, jint, jbyteArray, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     com_android_watermark_WaterMarkJni
 * Method:    yuvAddWaterMark
 * Signature: (JIII[BII[BII)V
 */
JNIEXPORT void JNICALL Java_com_android_watermark_WaterMarkJni_yuvAddWaterMark
  (JNIEnv *, jclass, jlong, jint, jint, jint, jbyteArray, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     com_android_watermark_WaterMarkJni
 * Method:    Nv21ClockWiseRotate90
 * Signature: (J[BII[B[I[I)V
 */
JNIEXPORT void JNICALL Java_com_android_watermark_WaterMarkJni_Nv21ClockWiseRotate90
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jbyteArray, jintArray, jintArray);

/*
 * Class:     com_android_watermark_WaterMarkJni
 * Method:    Nv21ClockWiseRotate180
 * Signature: (J[BII[B[I[I)V
 */
JNIEXPORT void JNICALL Java_com_android_watermark_WaterMarkJni_Nv21ClockWiseRotate180
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jbyteArray, jintArray, jintArray);

/*
 * Class:     com_android_watermark_WaterMarkJni
 * Method:    Nv21ClockWiseRotate270
 * Signature: (J[BII[B[I[I)V
 */
JNIEXPORT void JNICALL Java_com_android_watermark_WaterMarkJni_Nv21ClockWiseRotate270
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jbyteArray, jintArray, jintArray);

/*
 * Class:     com_android_watermark_WaterMarkJni
 * Method:    Nv12ClockWiseRotate90
 * Signature: (J[BII[B[I[I)V
 */
JNIEXPORT void JNICALL Java_com_android_watermark_WaterMarkJni_Nv12ClockWiseRotate90
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jbyteArray, jintArray, jintArray);

/*
 * Class:     com_android_watermark_WaterMarkJni
 * Method:    I420ClockWiseRotate90
 * Signature: (J[BII[B[I[I)V
 */
JNIEXPORT void JNICALL Java_com_android_watermark_WaterMarkJni_I420ClockWiseRotate90
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jbyteArray, jintArray, jintArray);

/*
 * Class:     com_android_watermark_WaterMarkJni
 * Method:    Yv12ClockWiseRotate90
 * Signature: (J[BII[B[I[I)V
 */
JNIEXPORT void JNICALL Java_com_android_watermark_WaterMarkJni_Yv12ClockWiseRotate90
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jbyteArray, jintArray, jintArray);

/*
 * Class:     com_android_watermark_WaterMarkJni
 * Method:    stopWaterMarkEngine
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_android_watermark_WaterMarkJni_stopWaterMarkEngine
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
